# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [80]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [81]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/UTPAL CHATTERJEE/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/UTPAL CHATTERJEE/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/UTPAL CHATTERJEE/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_li

#### 3. Create a null vector of size 10

In [82]:
a = np.zeros((10,))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [83]:
a1 = np.array([1, 2, 3, 4, 5])
print("%d bytes" % (a1.size * a1.itemsize))

20 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [84]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [85]:
b = np.zeros((10,))
b[4] = 1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [86]:
c = np.arange(10, 50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [87]:
d = np.array([1,2,3])
print(np.flip(d))

[3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [88]:
e = np.arange(0, 9).reshape((3, 3))
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [89]:
f = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(f))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [90]:
g = np.eye(3)
print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [91]:
h = np.random.random((3, 3, 3))
print(h)

[[[0.45476537 0.88177647 0.41235641]
  [0.95398693 0.0960141  0.84521595]
  [0.18834205 0.643906   0.60167004]]

 [[0.28220276 0.79293945 0.23957835]
  [0.21595009 0.35991872 0.49687169]
  [0.47317604 0.30824652 0.05407909]]

 [[0.04465636 0.8869472  0.91390874]
  [0.47883456 0.87851738 0.21151342]
  [0.15603522 0.23112568 0.67003975]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [92]:
i = np.random.random((10,))
minimum = np.min(i)
maximum = np.max(i)
print(minimum, maximum)

0.21366401567882443 0.9735031476464323


#### 14. Create a random vector of size 30 and find the mean value

In [93]:
j = np.random.random((30,))
mean = np.mean(j)
print(mean)

0.4961235579476201


#### 15. Create a 2d array with 1 on the border and 0 inside

In [94]:
k = np.ones((5, 5), dtype=np.int)
k[1:4,1:4] = 0
print(k)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [95]:
l = np.arange(1, 10).reshape(3,3)
l = np.pad(l, pad_width=1, constant_values=0)
print(l)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [96]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [97]:
m = np.diag(1+np.arange(4),k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [98]:
n = np.zeros((8, 8), dtype = int)
n[1::2,1::2] = 1
n[:8:2,:8:2] = 1
print(n)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [99]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
